language: erlang
env:
  global:
  - VERSION_NUMBER="`cat package.json | grep version | grep -o '[0-9]\.[0-9]\.[0-9]\+'`"
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - REAL_GIT_BRANCH="`git for-each-ref --format='%(objectname) %(refname:short)' refs/heads
    | grep $TRAVIS_COMMIT | awk '{print $2}'`"
  - ARCH=arm
script:
- sudo apt-get update -q
- sudo apt-get -y install docker
- docker run -t --rm --privileged -e "BUILD_NUMBER=0" -e "REAL_GIT_BRANCH=master" -v `pwd`:/src -v `pwd`/output:/out armhfcompiler ./packageforarm.sh

deploy:
  provider: s3
  access_key_id: AKIAIUN4NNHBKIOZE2JA
  secret_access_key:
    secure: YoK8n6Frgn4A0292Yu2yUiEsrL/hHUZnvxY9W5mfVyxHjoA1wz9qGdxlCsr81LxkKH5nUor1XGxcCaFj8jSGAdtaw6Fv+dBJv031QWSGqPxLchFxg2ioTTe7i/PcWE+9fIPEdrEKOAqdKM7v7vm+oikzuxmoksCS9m1p3TverEI=
  bucket: openrov-software-nightlies
  skip_cleanup: true
  region: us-west-2
  endpoint: bucket-name.s3-website-us-west-2.amazonaws.com
  local-dir: output
  upload-dir: openrov-cockpit
  acl: public_read
  on:
    repo: BrianAdams/openrov-software
